### PR TITLE
Create 2017-11-15-Control-winds.markdown

### PR DESCRIPTION
**Pull request by Eikrem63**

### CODE REVIEW

**Comment by Traneptora** [comment]
Please edit [https://github.com/thebombzen/grimoire/blob/master/_posts/2015-11-19-control-winds.markdown](https://github.com/thebombzen/grimoire/blob/master/_posts/2015-11-19-control-winds.markdown) rather than creating a new file.

**Comment by Eikrem63** [comment]
My mistake, I didn't realize it was a preexisting spell.

**Comment by Traneptora** [comment]
Did you make any changes? If not I'm going to close the PR. If so I'll leave it open.

**Comment by Eikrem63** [comment]
You can close the PR.

**Pull request closed without merging**
