### PR TITLE
Create 2017-11-15-dawn.markdown

### PR DESCRIPTION
**Pull request by Eikrem63**

### CODE REVIEW

**Comment by Traneptora** [comment]
You finally did it, no typos :)

**Comment by Eikrem63** [comment]
Firstly I'd like to thank my family, lol. Glad it didn't take Far Step to achieve this milestone.

**Comment by Traneptora** [comment]
Although you placed it in the wrong directory. I moved it to _posts.

**Comment by Eikrem63** [comment]
Alas. There is always something.

**Pull request merged**
